/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KcbpNativeMethod */

#ifndef _Included_KcbpNativeMethod
#define _Included_KcbpNativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_Init
 * Signature: (Ljava/lang/String;IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_KcbpNativeMethod_KCBPCLI_1Init
  (JNIEnv *, jobject, jstring, jint, jint, jstring, jstring, jstring);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SetOptions
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_KcbpNativeMethod_KCBPCLI_1SetOptions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SQLConnect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KcbpNativeMethod_KCBPCLI_1SQLConnect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_BeginWrite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_KcbpNativeMethod_KCBPCLI_1BeginWrite
  (JNIEnv *, jobject);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SetValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_KcbpNativeMethod_KCBPCLI_1SetValue
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SQLExecute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KcbpNativeMethod_KCBPCLI_1SQLExecute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_RsOpen
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KcbpNativeMethod_KCBPCLI_1RsOpen
  (JNIEnv *, jobject);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SQLFetch
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KcbpNativeMethod_KCBPCLI_1SQLFetch
  (JNIEnv *, jobject);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SQLGetColName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KcbpNativeMethod_KCBPCLI_1SQLGetColName
  (JNIEnv *, jobject, jint);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_RsGetCol
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KcbpNativeMethod_KCBPCLI_1RsGetCol
  (JNIEnv *, jobject, jint);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SQLMoreResults
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_KcbpNativeMethod_KCBPCLI_1SQLMoreResults
  (JNIEnv *, jobject);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_RsGetColByName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KcbpNativeMethod_KCBPCLI_1RsGetColByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SQLDisconnect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_KcbpNativeMethod_KCBPCLI_1SQLDisconnect
  (JNIEnv *, jobject);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_Exit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_KcbpNativeMethod_KCBPCLI_1Exit
  (JNIEnv *, jobject);

/*
 * Class:     KcbpNativeMethod
 * Method:    KDEncode
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KcbpNativeMethod_KDEncode
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     KcbpNativeMethod
 * Method:    KCBPCLI_SQLNumResultCols
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_KcbpNativeMethod_KCBPCLI_1SQLNumResultCols
  (JNIEnv *, jobject);

/*
 * Class:     KcbpNativeMethod
 * Method:    RsGetRowNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_KcbpNativeMethod_RsGetRowNum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
